Files:
  .vim/autoload/pathogen.vim:    http://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim
  .vim/plugin/BufGrep.vim:       http://git.jamessan.com/?p=etc/vim.git;a=blob_plain;f=plugin/BufGrep.vim;hb=HEAD
  .vim/plugin/manpageview1.vim:  http://github.com/godlygeek/vim-files/raw/master/plugin/manpageview.vim
  .vim/plugin/terminalkeys1.vim: http://github.com/godlygeek/vim-files/raw/master/plugin/terminalkeys.vim
  .vim/plugin/vsearch.vim:       http://github.com/godlygeek/vim-files/raw/master/plugin/vsearch.vim
  .vim/syntax/markdown.vim:      http://github.com/plasticboy/vim-markdown/raw/master/mkd.vim
  .vim/syntax/python1.vim:       http://www.hlabs.spb.ru/vim/python.vim
  .zsh/functions/_git:           http://zsh.cvs.sourceforge.net/viewvc/*checkout*/zsh/zsh/Completion/Unix/Command/_git
  .zsh/functions/_rake:          http://zsh.cvs.sourceforge.net/viewvc/*checkout*/zsh/zsh/Completion/Unix/Command/_rake
  .zsh/functions/_tmux:          http://zsh.cvs.sourceforge.net/viewvc/*checkout*/zsh/zsh/Completion/Unix/Command/_tmux

Bundles:
  .vim/bundles/abolish:     https://github.com/tpope/vim-abolish.git
  .vim/bundles/brew:        https://github.com/graywh/vim-brew.git
  .vim/bundles/bundler:     https://github.com/tpope/vim-bundler.git
  .vim/bundles/colorchart:  https://github.com/godlygeek/colorchart.git
  .vim/bundles/colorindent: https://github.com/graywh/vim-colorindent.git
  .vim/bundles/commentary:  https://github.com/tpope/vim-commentary.git
  .vim/bundles/csapprox:    https://github.com/godlygeek/csapprox.git
  .vim/bundles/dispatch:    https://github.com/tpope/vim-dispatch.git
  .vim/bundles/endwise:     https://github.com/tpope/vim-endwise.git
  .vim/bundles/fugitive:    https://github.com/tpope/vim-fugitive.git
  .vim/bundles/gist:        https://github.com/mattn/gist-vim.git
  .vim/bundles/git:         https://github.com/tpope/vim-git.git
  .vim/bundles/haml:        https://github.com/tpope/vim-haml.git
  .vim/bundles/ragtag:      https://github.com/tpope/vim-ragtag.git
  .vim/bundles/rails:       https://github.com/tpope/vim-rails.git
  .vim/bundles/rake:        https://github.com/tpope/vim-rake.git
  .vim/bundles/rbenv:       https://github.com/tpope/vim-rbenv.git
  .vim/bundles/ruby:        https://github.com/vim-ruby/vim-ruby.git
  .vim/bundles/scriptease:  https://github.com/tpope/vim-scriptease.git
  .vim/bundles/space:       https://github.com/spiiph/vim-space.git
  .vim/bundles/speeddating: https://github.com/tpope/vim-speeddating.git
  .vim/bundles/surround:    https://github.com/tpope/vim-surround.git
  .vim/bundles/tabular:     https://github.com/godlygeek/tabular.git
  .vim/bundles/webapi:      https://github.com/mattn/webapi-vim.git

# '<,'>Tab /:\zs /l0
# vim: isk+=46-47
